# Generated by Django 2.1.3 on 2018-12-11 07:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='postagem',
            options={'ordering': ['data']},
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='anexo',
            name='postagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anexo_postagem', to='social.Postagem'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='imagem',
            field=models.ImageField(default='group.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='grupo',
            name='usuarios',
            field=models.ManyToManyField(related_name='grupo_usuario', to='social.Usuario'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='questao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questao_postagem', to='social.Questao'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='amigos',
            field=models.ManyToManyField(related_name='amigos_usuario', to='social.Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(upload_to='anexos'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postagem_comentario', to='social.Postagem'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_comentario', to='social.Usuario'),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postagem',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_postagem', to='social.Usuario'),
        ),
        migrations.AddField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='social.Usuario'),
        ),
        migrations.AddField(
            model_name='convite',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to='social.Usuario'),
        ),
    ]
