# Generated by Django 2.1.3 on 2018-12-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20181211_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='imagem',
            field=models.ImageField(upload_to='grupos'),
        ),
    ]
