# Generated by Django 2.1.3 on 2018-12-11 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_auto_20181211_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='imagem',
            field=models.FileField(upload_to='grupos'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='usuarios',
            field=models.ManyToManyField(related_name='grupo_usuario', to='social.Usuario'),
        ),
    ]
