# Generated by Django 2.1.3 on 2018-12-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_auto_20181211_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grupo',
            old_name='imagem',
            new_name='img',
        ),
    ]
