# Generated by Django 2.1.3 on 2018-12-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20181211_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='descricao',
            field=models.TextField(),
        ),
    ]
