# Generated by Django 2.1.4 on 2019-01-03 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_auto_20190102_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='sem nome', max_length=128),
            preserve_default=False,
        ),
    ]
