# Generated by Django 2.1.4 on 2019-01-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_usuario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_empresa',
        ),
    ]
