# Generated by Django 2.1.4 on 2019-01-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_remove_usuario_nome_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome_empresa',
            field=models.CharField(default='Sem empresa', max_length=255),
            preserve_default=False,
        ),
    ]
