# Generated by Django 2.1.4 on 2019-01-05 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_usuario_nome_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome_empresa',
        ),
    ]
