# Generated by Django 2.1.4 on 2019-01-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_remove_usuario_nome_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], default='Outros', max_length=12),
            preserve_default=False,
        ),
    ]
