# Generated by Django 2.1.4 on 2019-01-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_usuario_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueados',
            field=models.ManyToManyField(related_name='usuarios_bloqueados', to='social.Usuario'),
        ),
    ]
