# Generated by Django 2.1.4 on 2019-01-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_usuario_bloqueados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='static/img/user.png', null=True, upload_to='profiles'),
        ),
    ]
