# Generated by Django 2.1.4 on 2019-01-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_auto_20190106_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='static/img/user.png', upload_to='profiles'),
        ),
    ]
