# Generated by Django 2.1.4 on 2019-01-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_auto_20190106_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='social/static/img/user.png', upload_to='profiles'),
        ),
    ]
