# Generated by Django 2.0.9 on 2019-01-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20190107_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='img/user.png    ', upload_to='profiles'),
        ),
    ]
