# Generated by Django 2.1.5 on 2019-01-25 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_auto_20190107_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desativo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='social.Usuario')),
            ],
        ),
    ]
