# Generated by Django 2.2a1 on 2019-01-25 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_desativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desativo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desativacao', to='social.Usuario'),
        ),
    ]
