# Generated by Django 2.1.5 on 2019-01-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_auto_20190125_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='profiles/user.png', upload_to='profiles'),
        ),
    ]
