# Generated by Django 2.0.10 on 2019-01-29 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0031_auto_20190127_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desativo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desativacao', to='social.Usuario'),
        ),
    ]
