# Generated by Django 2.1.5 on 2019-02-11 05:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_auto_20190129_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stories', models.ImageField(upload_to='stories')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories_usuario', to='social.Usuario')),
            ],
        ),
    ]
