# Generated by Django 2.1.7 on 2019-02-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_storie'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cidade',
            field=models.CharField(default='Teresina', max_length=128),
        ),
    ]
