# Generated by Django 2.0.5 on 2019-02-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_usuario_cidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cidade',
        ),
    ]
