# Generated by Django 2.0.5 on 2019-02-12 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0036_postagemcompartilhada'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='compartilhada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postagem',
            name='compartilhador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_compartilhador', to='social.Usuario'),
        ),
    ]
