# Generated by Django 2.0.5 on 2019-02-12 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0037_auto_20190212_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='data_compartilhada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
